sudo: required
dist: trusty
language: go
## home folder is /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli
services:
- docker
stages:
  - test
  - deploy

before_install:
- pwd
- bash --version
- sudo apt-get install --only-upgrade bash
- bash --version
- test/prepare.sh

env:
  - OPENSHIFT_VERSION=v3.10
  - TO_TEST=openshift-spark
  - TO_TEST=openshift-spark-py36
  - TO_TEST=openshift-spark-inc
  - TO_TEST=openshift-spark-py36-inc
  - TO_TEST=openshift-spark-spark-comp
  - TO_TEST=openshift-spark-py36-comp

jobs:
  include:
  - stage: test
    script:
    - if [ "$TO_TEST" = "openshift-spark" ]; then make test-e2e-py ; fi
    - if [ "$TO_TEST" = "openshift-spark-py36" ]; then make test-e2e-py36 ; fi
    - if [ "$TO_TEST" = "openshift-spark-inc" ]; then make -f Makefile.inc test-e2e-py ; fi
    - if [ "$TO_TEST" = "openshift-spark-py36-inc" ]; then make -f Makefile.inc test-e2e-py36 ; fi
    - if [ "$TO_TEST" = "openshift-spark-comp" ]; then make -f Makefile.inc test-e2e-py-completed ; fi
    - if [ "$TO_TEST" = "openshift-spark-py36-comp" ]; then make -f Makefile.inc test-e2e-py36-completed ; fi
  
  - stage: deploy
    name: "Push container images"
    script: ./.travis.release.images.sh
notifications:
 email:
   on_success: never
   on_failure: never
